# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"
  
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]  
        sdk: [sdk-baseline, sdk-global-json]
        exclude:
          - os: windows-latest
            sdk: sdk-baseline
    runs-on: ubuntu-latest
    name: Svelte .NET Aspire CI
    env:
      DOTNET_BASELINE_SDK_VERSION: '8.0.1xx'
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      DOTNET_MULTILEVEL_LOOKUP: false
      DOTNET_INSTALL_DIR: ${{ matrix.os == 'ubuntu-latest' && '' || 'dotnet' }}
      ASPIRE_ALLOW_UNSECURED_TRANSPORT: true
    steps:
    - uses: actions/checkout@v4

    - name: "Install .NET SDK (baseline: ${{ env.DOTNET_BASELINE_SDK_VERSION }})"
      if: matrix.os == 'ubuntu-latest' && matrix.sdk == 'sdk-baseline'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_BASELINE_SDK_VERSION }}

    - name: "Install .NET SDK (global.json)"
      if: matrix.sdk == 'sdk-global-json'
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ${{ matrix.os == 'ubuntu-latest' && './global.json' || '.\global.json' }}

    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'  
        
    - name: Install .NET Aspire workload
      run: dotnet workload install aspire

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      id: test
      if: matrix.os == 'ubuntu-latest'
      # Note that the space after the last double dash (--) is intentional
      run: >
        dotnet test 
        --no-build --verbosity normal
        --logger console --logger trx --logger html --logger GitHubActions
        --results-directory ./TestResults --blame
        -- 
        RunConfiguration.CollectSourceInformation=true

    - name: Publish Test Results
      if: (success() || steps.test.conclusion == 'failure') && matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: TestResults_${{ matrix.os }}_${{ matrix.sdk }}
        path: ./TestResults        